language: rust
env:
  global:
    - secure: VKmbEYVEpNwgrKvsjCx1JYCYNKDtG1uq+uDjScgcNuNQRUbWK7c7vsnupuxHTIL0543YXtxJlI8CAOmDUblANrtLSvo3O2FxpgMlvNvs3c98qk0a6tS1wy6vFhn1BbeaAPeaRtVzVqBY/2gqZLHzjGbA6sbH6sYkGN/HRSa/+J7jtYt5khk3S6AhpZglthtGipmNNXylB1WvhdD3XC9dmdxjmJOHDYI5tIlxpNrHsyChN9hTKubzKHaYrXS+g4rHZBO3qvDmOpYMIGe81bQAmBX+IzOBFU4gCgQOrVZcr5BxSG+zmoNtAkAKYV/0ZUIbAhcz893MIBHgMRXrUQDtV0WyhXQZVaml3AntGY5wOM1n+WRfMl8dvpblTqSxRKrJCde9UUAsDzuDliXxeaRyrimTTyzo6oE5850KnFExL6fiTM+j8ZgN5KAzKKEhh8c/KCaJy0iQA0RwWBcB8P/MdhdXXFtjgDlOuYN8Tp9ZIpkFX6lT1wCUGuNXpvhNPEsJiuvNFWDEYJrVvHeMwJNyNcFifBR3WBnibxt+QS3uH6UBZUDHa9lmmANPCrjosPKdb3QKj+NEXd67s0ksflaIQiEBibs8S6WcvtadmI2Y7UtsOq9aZuvsItba7QvDZQHyiHYHcRDxwGoVuTbwfG/8MP2KZe6DenhsbRLoGqCyXco=

install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install v10.5
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

cache: cargo

jobs:
  include:
    - stage: Deploy
      deploy:
        - provider: script
          skip_cleanup: true
          script: bash deploy.sh
          on:
            branch: dev
