language: rust

rust:
  - stable

env:
  global:
    - CARGO_TARGET_DIR=$HOME/.cargo/target
    - secure: VKmbEYVEpNwgrKvsjCx1JYCYNKDtG1uq+uDjScgcNuNQRUbWK7c7vsnupuxHTIL0543YXtxJlI8CAOmDUblANrtLSvo3O2FxpgMlvNvs3c98qk0a6tS1wy6vFhn1BbeaAPeaRtVzVqBY/2gqZLHzjGbA6sbH6sYkGN/HRSa/+J7jtYt5khk3S6AhpZglthtGipmNNXylB1WvhdD3XC9dmdxjmJOHDYI5tIlxpNrHsyChN9hTKubzKHaYrXS+g4rHZBO3qvDmOpYMIGe81bQAmBX+IzOBFU4gCgQOrVZcr5BxSG+zmoNtAkAKYV/0ZUIbAhcz893MIBHgMRXrUQDtV0WyhXQZVaml3AntGY5wOM1n+WRfMl8dvpblTqSxRKrJCde9UUAsDzuDliXxeaRyrimTTyzo6oE5850KnFExL6fiTM+j8ZgN5KAzKKEhh8c/KCaJy0iQA0RwWBcB8P/MdhdXXFtjgDlOuYN8Tp9ZIpkFX6lT1wCUGuNXpvhNPEsJiuvNFWDEYJrVvHeMwJNyNcFifBR3WBnibxt+QS3uH6UBZUDHa9lmmANPCrjosPKdb3QKj+NEXd67s0ksflaIQiEBibs8S6WcvtadmI2Y7UtsOq9aZuvsItba7QvDZQHyiHYHcRDxwGoVuTbwfG/8MP2KZe6DenhsbRLoGqCyXco=

install:
  - mkdir -p ~/.cargo/target
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install v10.5
  - ./install.sh

cache: cargo

stages:
  - test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: test
      script: yarn test
      name: "Test WASM"
    - script: cargo test
      name: "Test Rust"
    - stage: deploy
      script: echo "deploying to NPM..."
      name: "Deploy to NPM"
      deploy:
        - provider: script
          skip_cleanup: true
          script: bash deploy.sh
          on:
            tags: true
    - script: echo "deploying to crates.io..."
      name: "Deploy to Crates.io"
      deploy:
        - provider: cargo
          skip_cleanup: true
          token:
            secure: NJ2lWYy8Lgr3aKFk+F+p+d6EATtXRSNebI8C1VVk5I+arXBOV4sUPqzOX2bptPKEuPhgN05c7g08GdisZjhnHSNnRQcNd9eolCY+J9VApXHlBbC9Snp6wqmciOZPqfNvEb6w+uYMvSxdsExSCX1c/7VJec7/AEykTPOvbnrgHAfCGT7ha17UYpjQQk249rPKZ52YZ6DrpX9eUWG1H/1Gyi9OXLE2xhXS0db6YQXzX2tqE2yLp7z7GFWTzxJxe7xcrYptNu2+RAin1rHb6Yq0VWU6rroaIXFQozfCIm3HEQjh7aFKCUy4ggjPqF3RPkY/E0bnuXxmq0ZFzGr3sbHnOe7odHttXTLA88O7A91gntAJsxrzRaXgkrx4eWZV6KWwg5F1HGOj3p3l5308DotaeG6AEQls9bpvx+tEWYvXYAwcqU3ZYkFnQCJYff3P4HqQTuICu6iz4jWvY/CBYBW85Aakzed3bs5GL9kEaOu6cNniTqRewlBhHNSDax1H2B4vc9p3SLFjFK3Y6jrb/AL4rQooyNxqZsz0XPtS7+yW80mTsQ7EKk1pTSWhFJk+BGfWbPP4lF6MxaLzU99Q80u18qbm4J+GPRX5GZ1BvfM/YVn3cji49uRV5AdPX/Qg47nBXcQyhubk90bNijgw+jl4v2yh000JO4wyrvy3C5qi71k=
          on:
            tags: true
