[package]
authors = ["Mario Reder <mreder1289@gmail.com>"]
categories = ["wasm", "emulators"]
description = "A utility library for Super Mario Maker and Super Mario Maker 2 to read and manipulate game files."
edition = "2018"
license = "MIT"
name = "smmdb"
readme = "./README.md"
repository = "https://github.com/Tarnadas/cemu-smm"
version = "1.0.2"
include = [
    "/src/**/*.rs",
    "/proto/**/*.proto",
    "/build.rs",
    "/Cargo.toml",
    "/README.md",
    "/LICENSE"
]

[build-dependencies]
protobuf-codegen-pure = "2.16"

[dependencies]
aes-soft= "0.4"
arr_macro = { version = "0.1", optional = true}
arrayref = "0.3"
block-modes = "0.5"
byteorder = "1.3"
cfg-if = "0.1"
chrono = "0.4"
cmac = "0.3"
crc = "1.8"
failure = "0.1"
generic-array = {version = "0.14", optional = true }
image = "0.23"
infer = "0.2"
itertools = "0.9"
rand = "0.7"
serde = "1.0"
serde_derive = "1.0"
typenum = "1.12"

[dependencies.bytes]
features = ["serde"]
version = "0.5"

[dependencies.console_error_panic_hook]
optional = true
version = "0.1.6"

[dependencies.js-sys]
optional = true
version = "0.3"

[dependencies.protobuf]
features = ["with-bytes", "with-serde"]
version = "2.16"

[dependencies.regex]
version = "1.3"

[dependencies.wasm-bindgen]
features = ["serde-serialize"]
optional = true
version = "0.2"

[dependencies.web-sys]
features = ["console", "Document", "Element", "HtmlElement", "Node", "Window"]
optional = true
version = "0.3"

[dependencies.wee_alloc]
optional = true
version = "0.4"

[dependencies.zip]
default-features = false
features = ["deflate"]
version = "0.5"

[dev-dependencies]
wasm-bindgen-test = "0.3"

[features]
default = ["with-serde"]
wasm = ["console_error_panic_hook", "js-sys", "wasm-bindgen", "web-sys"]
with-serde = []
save = ["arr_macro", "generic-array"]

[lib]
crate-type = ["cdylib", "rlib"]
name = "smmdb"
path = "src/lib.rs"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[profile]
[profile.release]
debug = false
lto = true
codegen-units = 1
