[package]
authors = ["Mario Reder <mreder1289@gmail.com>"]
categories = ["wasm"]
description = "This is a module to simplify all kinds of tasks with Loadiine Super Mario Maker save files and respectively Cemu"
license = "MIT"
name = "cemu-smm"
readme = "./README.md"
repository = "https://github.com/Tarnadas/cemu-smm"
version = "4.0.1"
build = "build.rs"

[dependencies]
cfg-if = "0.1.7"
js-sys = "=0.3.15"
protobuf = "2.4"
wasm-bindgen = "=0.2.38"

[dependencies.console_error_panic_hook]
optional = true
version = "0.1.6"

[dependencies.web-sys]
features = ["Document", "Element", "HtmlElement", "Node", "Window"]
version = "=0.3.15"

[dependencies.wee_alloc]
optional = true
version = "0.4.3"

[build-dependencies]
protoc-rust = "2.0"
protobuf-codegen-pure = "2.3"

[features]
default = ["console_error_panic_hook"]

[lib]
crate-type = ["cdylib"]
path = "crate/src/lib.rs"

[profile]
[profile.release]
debug = false
lto = true
