[package]
authors = ["Mario Reder <mreder1289@gmail.com>"]
categories = ["wasm", "emulators"]
description = "A utility library for Super Mario Maker and possibly Super Mario Maker 2 in the future to read and manipulate game files."
edition = "2018"
license = "MIT"
name = "cemu-smm"
readme = "./README.md"
repository = "https://github.com/Tarnadas/cemu-smm"
version = "4.0.12"
include = [
    "/crate/src/**/*.rs",
    "/proto/**/*.proto",
    "/build.rs",
    "/Cargo.toml",
    "/README.md",
    "/LICENSE"
]

[[bin]]
name = "cemu-smm"
path = "crate/src/main.rs"

[build-dependencies]
protobuf-codegen-pure = "2.8"

[dependencies]
aes-soft= "0.3"
block-modes = "0.3"
byteorder = "1.3"
cfg-if = "0.1.9"
chrono = "0.4"
compression = "0.1"
failure = "0.1"
image = "0.22"
itertools = "0.8"
js-sys = "=0.3.25"
mime = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tree_magic = "0.2"
typenum = "1.10"

[dependencies.bytes]
features = ["serde"]
version = "0.4"

[dependencies.console_error_panic_hook]
optional = true
version = "0.1.6"

[dependencies.protobuf]
features = ["with-bytes", "with-serde"]
version = "2.8"

[dependencies.regex]
features = ["pattern"]
version = "1.2"

[dependencies.wasm-bindgen]
features = ["serde-serialize"]
version = "=0.2.48"

[dependencies.web-sys]
features = ["console", "Document", "Element", "HtmlElement", "Node", "Window"]
version = "=0.3.25"

[dependencies.wee_alloc]
optional = true
version = "0.4"

[dependencies.zip]
default-features = false
features = ["deflate"]
version = "0.5"

[dev-dependencies]
wasm-bindgen-test = "=0.2.48"

[features]
default = ["console_error_panic_hook", "with-serde"]
with-serde = []

[lib]
crate-type = ["cdylib", "rlib"]
name = "cemu_smm"
path = "crate/src/lib.rs"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[profile]
[profile.release]
debug = false
lto = true
