[package]
authors = ["Mario Reder <mreder1289@gmail.com>"]
categories = ["wasm"]
description = "This is a module to simplify all kinds of tasks with Loadiine Super Mario Maker save files and respectively Cemu"
edition = "2018"
license = "MIT"
name = "cemu-smm"
readme = "./README.md"
repository = "https://github.com/Tarnadas/cemu-smm"
version = "4.0.1"

[[bin]]
name = "cemu-smm"
path = "crate/src/main.rs"

[build-dependencies]
protobuf-codegen-pure = "2.4"

[dependencies]
cfg-if = "0.1.7"
js-sys = "=0.3.15"
serde = "1.0"
serde_derive = "1.0"

[dependencies.bytes]
features = ["serde"]
version = "0.4"

[dependencies.console_error_panic_hook]
optional = true
version = "0.1.6"

[dependencies.protobuf]
features = ["with-bytes", "with-serde"]
version = "2.4"

[dependencies.wasm-bindgen]
features = ["serde-serialize"]
version = "=0.2.38"

[dependencies.web-sys]
features = ["console", "Document", "Element", "HtmlElement", "Node", "Window"]
version = "=0.3.15"

[dependencies.wee_alloc]
optional = true
version = "0.4.3"

[dev-dependencies]
wasm-bindgen-test = "=0.2.38"

[features]
default = ["console_error_panic_hook", "with-serde"]
with-serde = []

[lib]
name = "cemu_smm"
crate-type = ["cdylib", "rlib"]
path = "crate/src/lib.rs"

[profile]
[profile.release]
debug = false
lto = true
